# Generated by Django 3.0.5 on 2020-05-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200507_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
